apiVersion: v1
kind: PersistentVolume
metadata:
  name: dependency-check-nvd-cache-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Path on the host node for persistence
    path: <YOUR_HOST_PATH_DIRECTORY> # e.g. /data/dependency-check-nvd-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                # Hostname of the target worker node where directory is located
                - <YOUR_NODE_HOSTNAME> # e.g. dell6500t
