apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-check-nvd-cache
  namespace: dependency-check
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
